### ISSUE TITLE
Point Limits Problem

### ISSUE THREAD

**Issue by sunhailin-Leo** [sulewicz/redis-s2geo#3]
I`m so curious about this definition at `https://github.com/sulewicz/redis-s2geo/blob/main/src/parser.cc#L10`, why set this limit to 64? ❓ 

* Another Question:
Did you have any roadmap to continue to maintain this repo?  I`m so curious about the `POINTSEARCH` with the return of a list of polygons.
* Reason:
I have a lot of polygon data but I can ensure that none of the polygons overlap, but when I use the `POINTSEARCH` I find that the results return a lot of data, which is very confusing.

**Comment by sulewicz** [comment]
Hello!

The point limit is arbitrary, it should be possible to increase it without any side effects.

Regarding your second question, if you get a lot of matches in response to POINTSEARCH, it is possible that the winding of your polygons is incorrect (see [details](https://macwright.com/2015/03/23/geojson-second-bite.html#winding)). The polygon points need to be in counterclockwise order, otherwise everything outside the polygon will be considered a part of it (as in this [old joke](https://pastebin.com/raw/YQEQJPjK) about a mathematician).

The easiest way to test it is to put a single polygon in the collection and use POINTSEARCH with one point that you know for sure is outside of it and one inside of the polygon. If POINTSEARCH with a point outside of the polygon produces a result, it will confirm the winding is not correct. In that case, there is a couple of libraries that you can use to fix your data set, e.g., https://github.com/mapbox/geojson-rewind.

If that does not solve your problem, feel free to provide some sample data, so we can debug further.

**Comment by sunhailin-Leo** [comment]
> 

@sulewicz 

Your suggestion is useful to me! 😊 The problem is actually caused by the counterclockwise order. 

So I try to use the python shapely package `https://shapely.readthedocs.io/en/stable/manual.html#shapely.geometry.polygon.orient` to correct my polygon data, then after `POINTSEARCH` returned the right answer for me.

Thank you for your reply!

**Comment by sulewicz** [comment]
I am glad it helped! :)
